# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16i4SO-BVBpZ6L71PYCL-vWBDODjh7dkD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("Mall_Customers.csv")
dataset.head()

dataset.info()

dataset.describe()

dataset=dataset.replace({'Gender':{'Male':1, 'Female':0}})

dataset.head()

dataset=dataset.drop(columns=['CustomerID'])

X=dataset.iloc[:,2:4].values

print(X)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#X=sc.fit_transform(X)

from sklearn.cluster import KMeans
wcss=[]
for i in range(1,10):
    model= KMeans(n_clusters=i, random_state=42)
    model.fit_transform(X)
    wcss.append(model.inertia_)
plt.plot(wcss, color='blue', linewidth=2)

model= KMeans(n_clusters=5)
model.fit(X)
y_labels=model.labels_
centroids=model.cluster_centers_

centroids

col=['b','g','r','c','y']
for i in range(0,5):
    plt.scatter(X[y_labels==i,0],X[y_labels==i,1],c=col[i], linewidths=2, label="Cluster"+str(i+1))
plt.scatter(centroids[:,0],centroids[:,1], c='m', linewidths=5,label='Centroids')
plt.legend()